apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: op-stack
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    # Monitor Kubernetes pods
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - op-stack
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
    
    # Monitor Kubernetes services
    - job_name: 'kubernetes-services'
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
          - op-stack
    
    # Monitor Prometheus itself
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
