name: Pull Request Checks

on:
  pull_request:
    branches: [main]

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check PR title format
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        if [[ ! "$PR_TITLE" =~ ^(feat|fix|docs|chore):.* ]]; then
          echo "❌ PR title must start with: feat:, fix:, docs:, or chore:"
          exit 1
        fi
        echo "✅ PR title follows convention"
