name: Pull Request Checks

on:
  pull_request:
    branches: [main]

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check PR title format
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        echo "Checking PR title: '$PR_TITLE'"
        if [[ "$PR_TITLE" =~ ^(feat|fix|docs|chore|test):.* ]]; then
          echo " PR title follows convention"
        else
          echo " PR title must start with: feat:, fix:, docs:, chore:, or test:"
          echo "Current title: $PR_TITLE"
          exit 1
        fi
